version: "2.0"

services:
    api_test_php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: api_test_php
        restart: always
        working_dir: /var/www/html/
#        command: php /var/www/html/src/public/server.php
        # ports:
#        ports:
#             - 9501:9501
        volumes:
            # - /usr/share/zoneinfo/PRC:/etc/localtime
#            - ../src/:/var/www/html/
            - ../:/var/www/html
    api_test_nginx:
        image: nginx:1.13.3
        container_name: api_test_nginx
        restart: always 
        ports:
            - 9999:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ../:/var/www/html

    mysql:
        image: mysql:5.7.29
        container_name: mysql5-7-29
        restart: always
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: wibo
        ports:
            - 3306:3306
        volumes:
            - /data/mysql:/var/lib/mysql
    redis:
        image: redis:5.0.7
        container_name: redis
        volumes:
            - /usr/share/zoneinfo/PRC:/etc/localtime
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        ports:
            - 6379:6379
        command: redis-server  /usr/local/etc/redis/redis.conf
        restart: always